# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: 1669644663254564
  omniauth_provider_secret: c84b2190e08c234d146b9ab426f67a9a
  domain_name: example.com
  secret_key_base: 56aaedd80e875c83d7cb40be12379a51df4e15ebf0f85a2fa3edee9b4b8975e5d53c00f5e78ec30e77bc592d59ad45a8c2756a70aeb35ef037e3a2d7beba3f55

test:
  secret_key_base: 440dac24207bb69f2e0a8f94b199d5f6382fa62bc90012fc78cf26e5858a5d89f95a85a52e728fbdc5f69d0fabb4cd948cc60f94d088725455d966a3068c7710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: 1671110993107931
  omniauth_provider_secret: c9c74957f828981a407b778120d4febe 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
